version: '3.8'
services:
  library_strm:
    container_name: library_strm
    # command: python /alipan_strm/test.py
    image: thsrite/library-strm:latest
    ports:
      - 33455:33455
    volumes:
      - /home/root/Documents/emby/embyLibrary:/data
      - ./log:/log
      - ./config.yaml:/mnt/config.yaml
      - ./alipan_strm/test.py:/alipan_strm/test.py
      - ./alipan_strm/filechange.py:/alipan_strm/filechange.py
      - ./alipan_strm/main.py:/alipan_strm/main.py
    restart: unless-stopped
